applications:
- name: config-test
  instances: 1
  memory: 1024M
  disk_quota: 1024M
  routes:
  - route: config-test.cfapps.io
  stack: cflinuxfs2
  path: build/libs/spring-configure-0.0.1-SNAPSHOT.jar
  env: 
    SPRING_PROFILES_ACTIVE: dev1
